{{name}}:
  build: ./dockerfiles/dev
  command: lein do clean, repl :headless
  links:
    - db
  ports:
    - "80:3000"
    - "4001:4001"
  volumes:
    - ./:/app
    - ~/.m2/:/root/.m2/
  environment:
    - IS_DEV=true
    - DB_HOST=db
    - DB_USER=postgres
    - DB_NAME={{name}}
    - DB_PASS=changeme
    - MAILGUN_APIKEY=YOUR-KEY
    - MAILGUN_DOMAIN=YOUR-DOMAIN
    - DOMAIN=localhost
    - STRIPE_AUTH=YOUR-AUTH

figwheel:
  build: ./dockerfiles/dev
  command: lein figwheel
  stdin_open: true #figwheel requires a tty
  volumes:
    - ./:/app
    - ~/.m2/:/root/.m2/
  ports:
    - "3449:3449"

db:
  image: postgres:9.4.6
  volumes_from:
    - data
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_PASSWORD=changeme
    - POSTGRES_USER=postgres
    - POSTGRES_DB={{name}}

data:
  image: postgres:9.4.6
  command: /bin/true
